version: '3.8'

services:
   mixrech:
      build: ./mixrech
      command: gunicorn mixrech.wsgi:application --bind 0.0.0.0:8000 --timeout 120
      volumes:
      - .:/app
      ports:
         - "8000:8000"

   mixremail:
      build: ./mixrech
      command: gunicorn mixremail.wsgi:application --bind 0.0.0.0:8000 --timeout 120
      volumes:
      - .:/app
      ports:
         - "8001:8001"

   mixchat:
      build: ./mixrech
      command: gunicorn mixchat.wsgi:application --bind 0.0.0.0:8000 --timeout 120
      volumes:
      - .:/app
      ports:
         - "8002:8002"
         
   nginx:
      image: nginx:1.25.3
      volumes:
         - ./nginx.conf:/etc/nginx/nginx.conf:ro
         - ./staticfiles:/app/staticfiles/
         - /etc/ssl/certs/mixrech.crt:/etc/ssl/certs/mixrech.crt
         - /etc/ssl/private/private.key:/etc/ssl/private/privkey.key
         - /etc/ssl/certs/intermediate.crt:/etc/ssl/certs/intermediate.crt
         
      depends_on:
        - web
      ports:
        - "80:80"
        - "443:443"
