user www-data;
worker_processes 1;  # Количество рабочих процессов

events {
    worker_connections 1024;  # Максимальное количество соединений на рабочий процесс
}

http {
    include /etc/nginx/mime.types;  # Включение типов MIME (по желанию)
    default_type application/octet-stream;  # Установка типа по умолчанию

    server {
        listen 80;
        server_name www.porno-chrum.com;
        return 301 https://porno-chrum.com$request_uri;
    }

    server {
        listen 443 ssl;
        ssl_certificate /etc/ssl/certs/fullchain.pem;
        ssl_certificate_key /etc/ssl/private/privkey.pem;
        server_name porno-chrum.com;

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        location /static/ {
            alias /app/staticfiles/;
            try_files $uri $uri/ =404;
        }

        location / {
            proxy_pass http://158.160.133.169:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            error_page 404 /404.html;
            error_page 500 502 503 504 /50x.html;

            location = /50x.html {
                root html;
            }
        }
    }
}
