user www-data;
worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # Первый сервер для редиректа с HTTP на HTTPS для основного домена
    server {
        listen 80;
        server_name mixrech.com www.mixrech.com;
        return 301 https://mixrech.com$request_uri;
    }

    # Сервер для HTTPS основного домена
    server {
        listen 443 ssl;
        server_name mixrech.com www.mixrech.com;

        ssl_certificate /etc/letsencrypt/live/mixrech.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/mixrech.com/privkey.pem;
        ssl_trusted_certificate /etc/letsencrypt/live/mixrech.com/fullchain.pem;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:!RC4:!MD5:!aNULL:!EXPORT:!DES:!3DES:!CAMELLIA:!SEED:!IDEA:!RC4';
        ssl_prefer_server_ciphers on;

        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

        ssl_stapling on;
        ssl_stapling_verify on;

        resolver 8.8.8.8 8.8.4.4 valid=300s;
        resolver_timeout 5s;

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        location /static/ {
            alias /app/staticfiles/mixrech/;
            try_files $uri $uri/ =404;
        }

		location ~* /(phpmyadmin|PMA|dbadmin|admin) {
    		return 444;
		}

        location / {
            proxy_pass http://37.252.19.194:8000; # ваш Django сервер
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            error_page 404 /404.html;
            error_page 500 502 503 504 /50x.html;

            location = /50x.html {
                root html; 
            }
        }
    }

    # Сервер для редиректа с HTTP на HTTPS для chat.mixrech.com
    server {
        listen 80;
        server_name chat.mixrech.com;
        return 301 https://$host$request_uri; 
    }

    # Сервер для HTTPS chat.mixrech.com
    server {
        listen 443 ssl;
        server_name chat.mixrech.com;

        ssl_certificate /etc/letsencrypt/live/mixrech.com/fullchain.pem; # или другой сертификат для chat
        ssl_certificate_key /etc/letsencrypt/live/mixrech.com/privkey.pem;

        ssl_trusted_certificate /etc/letsencrypt/live/mixrech.com/fullchain.pem;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:!RC4:!MD5:!aNULL:!EXPORT:!DES:!3DES:!CAMELLIA:!SEED:!IDEA:!RC4';
        ssl_prefer_server_ciphers on;

        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

        ssl_stapling on;
        ssl_stapling_verify on;

        resolver 8.8.8.8 8.8.4.4 valid=300s;
	resolver_timeout 5s;

	access_log /var/log/nginx/access.log;
	error_log /var/log/nginx/error.log;

	location /static/ {
	    alias /app/staticfiles/mixchat/; 
	    try_files $uri $uri/ =404; 
	}

	location /media/ {
	    alias /app/media/;
	}

	location / {
	    proxy_pass http://37.252.19.194:8001;  
	    proxy_set_header Host $host; 
	    proxy_set_header X-Real-IP $remote_addr; 
	    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
	    proxy_set_header X-Forwarded-Proto $scheme; 
	    proxy_set_header Cookie $http_cookie; 

	    error_page 404 /404.html; 
	    error_page 500 502 503 504 /50x.html; 
	}

	location = /50x.html {
	    root html; 
	}
  }
}








