# Generated by Django 5.1.1 on 2026-05-06 21:28

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(verbose_name='Имя')),
                ('photo', models.ImageField(blank=True, default='photo/profilephoto/default.png', upload_to='photo/profilephoto/', verbose_name='Фотография')),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(verbose_name='Название')),
                ('photo', models.ImageField(blank=True, default='photo/profilephoto/default.png', null=True, upload_to='photo/profilephoto/', verbose_name='Фотография чата')),
                ('bio', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название чата')),
                ('photo', models.ImageField(blank=True, default='photo/profilephoto/default.png', null=True, upload_to='photo/profilephoto/', verbose_name='Фотография чата')),
                ('bio', models.TextField(verbose_name='Описание')),
                ('type', models.TextField(verbose_name='Тип')),
            ],
        ),
        migrations.CreateModel(
            name='ChatUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nickname', models.URLField(unique=True, verbose_name='Никнейм')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('phone', models.CharField(verbose_name='Телефон')),
                ('country_code', models.CharField(verbose_name='Код страны')),
                ('code', models.IntegerField(default=0, verbose_name='Код подтверждения')),
                ('photo', models.ImageField(blank=True, default='photo/profilephoto/default.png', upload_to='photo/profilephoto/', verbose_name='Фотография')),
                ('date_birth', models.DateField(blank=True, null=True)),
                ('bio', models.CharField(blank=True, null=True)),
                ('fcm_token', models.CharField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ChannelMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message_type', models.TextField(verbose_name='Тип')),
                ('content', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='messages/images/', verbose_name='Картинка')),
                ('video', models.FileField(blank=True, null=True, upload_to='messages/videos/', verbose_name='Видео')),
                ('audio', models.FileField(blank=True, null=True, upload_to='messages/audios/', verbose_name='Аудио')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('is_edit', models.BooleanField(blank=True, null=True, verbose_name='Редактировано?')),
                ('is_forwarded', models.BooleanField(null=True, verbose_name='Переслано?')),
                ('answer_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.channelmessage')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_messages', to='main.channel')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_channel', to='main.channelmessage')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelMembership',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_role', models.TextField(verbose_name='Роль пользователя')),
                ('chanel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chanel_id', to='main.channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField()),
                ('user_role', models.TextField(verbose_name='Роль пользователя')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_chat', to='main.chat')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message_type', models.TextField(verbose_name='Тип')),
                ('content', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='messages/images/', verbose_name='Картинка')),
                ('video', models.FileField(blank=True, null=True, upload_to='messages/videos/', verbose_name='Видео')),
                ('audio', models.FileField(blank=True, null=True, upload_to='messages/audios/', verbose_name='Аудио')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('is_edit', models.BooleanField(blank=True, null=True, verbose_name='Редактировано?')),
                ('is_forwarded', models.BooleanField(null=True, verbose_name='Переслано?')),
                ('answer_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.message')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='main.chat')),
                ('sender_bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='main.bot', verbose_name='Бот отправитель')),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь отправитель')),
            ],
        ),
        migrations.CreateModel(
            name='DeletedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_type', models.TextField(verbose_name='Тип удаления')),
                ('delete_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата удаления')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delete_chat_messages', to='main.chat')),
                ('deleted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_user', to=settings.AUTH_USER_MODEL, verbose_name='Удалил')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_deleted', to='main.message')),
            ],
        ),
        migrations.CreateModel(
            name='MessageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_message', models.TextField(verbose_name='Старое сообщение')),
                ('new_message', models.TextField(verbose_name='Новое сообщение')),
                ('old_date', models.DateTimeField(verbose_name='Старая дата')),
                ('new_date', models.DateTimeField(auto_now_add=True, verbose_name='Новая дата')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_chat_messages', to='main.chat')),
                ('edited', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edited_user', to=settings.AUTH_USER_MODEL, verbose_name='Отредактировал')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_history', to='main.message')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerChannelMessage',
            fields=[
                ('channelmessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.channelmessage')),
                ('channel_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_channel', to='main.channelchat')),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_channel_messages', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь отправитель')),
            ],
            bases=('main.channelmessage',),
        ),
    ]
