# Generated by Django 5.1.1 on 2026-05-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_forwarded',
            field=models.BooleanField(null=True, verbose_name='Переслано?'),
        ),
    ]
