# Generated by Django 5.1.1 on 2026-05-07 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='delete_at_home',
        ),
        migrations.RemoveField(
            model_name='message',
            name='id_for_answer',
        ),
        migrations.RemoveField(
            model_name='message',
            name='id_for_transmission',
        ),
        migrations.RemoveField(
            model_name='message',
            name='transmission_content',
        ),
        migrations.AddField(
            model_name='channel',
            name='bio',
            field=models.TextField(default=0, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channel',
            name='photo',
            field=models.ImageField(blank=True, default='photo/profilephoto/default.png', null=True, upload_to='photo/profilephoto/', verbose_name='Фотография канала'),
        ),
        migrations.AddField(
            model_name='channelmembership',
            name='user_role',
            field=models.TextField(default=0, verbose_name='Роль пользователя'),
            preserve_default=False,
        ),

        migrations.AddField(
            model_name='message',
            name='answer_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.TextField(default=0, verbose_name='Тип'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='is_forwarded',
            field=models.BooleanField(null=True, verbose_name='Пересылка?'),
        ),
        migrations.CreateModel(
            name='ChannelMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message_type', models.TextField(verbose_name='Тип')),
                ('content', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='messages/images/', verbose_name='Картинка')),
                ('video', models.FileField(blank=True, null=True, upload_to='messages/videos/', verbose_name='Видео')),
                ('audio', models.FileField(blank=True, null=True, upload_to='messages/audios/', verbose_name='Аудио')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('is_edit', models.BooleanField(blank=True, null=True, verbose_name='Редактировано?')),
                ('is_forwarded', models.BooleanField(null=True, verbose_name='Переслано?')),
                ('answer_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.channelmessage')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_messages', to='main.channel')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_channel', to='main.channelmessage')),
            ],
        ),
        migrations.CreateModel(
            name='DeletedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_type', models.TextField(verbose_name='Тип удаления')),
                ('delete_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата удаления')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delete_chat_messages', to='main.chat')),
                ('deleted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_user', to=settings.AUTH_USER_MODEL, verbose_name='Удалил')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_deleted', to='main.message')),
            ],
        ),
        migrations.CreateModel(
            name='MessageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_message', models.TextField(verbose_name='Старое сообщение')),
                ('new_message', models.TextField(verbose_name='Новое сообщение')),
                ('old_date', models.DateTimeField(verbose_name='Старая дата')),
                ('new_date', models.DateTimeField(auto_now_add=True, verbose_name='Новая дата')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_chat_messages', to='main.chat')),
                ('edited', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edited_user', to=settings.AUTH_USER_MODEL, verbose_name='Отредактировал')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_history', to='main.message')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerChannelMessage',
            fields=[
                ('channelmessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.channelmessage')),
                ('channel_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_channel', to='main.channelchat')),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_channel_messages', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь отправитель')),
            ],
            bases=('main.channelmessage',),
        ),
    ]
