# Generated by Django 5.1.1 on 2026-05-19 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_message_delete_at_home_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagehistory',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='messagehistory',
            name='edited',
        ),
        migrations.RemoveField(
            model_name='messagehistory',
            name='message',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_edit',
        ),
        migrations.AddField(
            model_name='message',
            name='is_change',
            field=models.BooleanField(blank=True, null=True, verbose_name='Изменён?'),
        ),
        migrations.DeleteModel(
            name='DeletedMessage',
        ),
        migrations.DeleteModel(
            name='MessageHistory',
        ),
    ]
