from django.urls import path
from . import views, api
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView


urlpatterns = [
    path('', views.chat, name='chat_url'),
    path('auth_in_chat', views.auth_in_chat, name='auth_in_chat'),
    path('register_in_chat', views.register_in_chat, name='register_in_chat'),
    path('successfully', views.successfully, name='successfully'),
    path('confirmation_code', views.confirmation_code, name='confirmation_code'),
    path('privacy_policy', views.privacy_policy, name='privacy_policy'),
    path('agreement', views.agreement, name='agreement'),
    path('profile_current_user', views.profile_current_user, name='profile_current_user'),
    path('profile_other_user/<str:username>', views.profile_other_user, name='profile_other_user'),
    path('create_group', views.create_group, name='create_group'),
    path('edit_group/<int:name>', views.edit_group, name='edit_group'),
    path('chat_profile/<int:name>', views.chat_profile, name='chat_profile'),
    path('media/<path:file_name>', api.LoadMediaView.as_view(), name='defense_media'),
    path('api/reg/', api.RegisterView.as_view(), name='reg'),
    path('api/send_code/', api.SendCodeView.as_view(), name='send_code'),
    path('api/resend_code/', api.ResendCodeView.as_view(), name='resend_code'),
    path('api/profile_form/', api.ProfileformView.as_view(), name='profile_form'),
    path('api/save_mqtt/', api.SaveMqttView.as_view(), name='save_mqtt'),
    path('api/check_mqtt/', api.CheckMqttView.as_view(), name='check_mqtt'),
    path('api/message/', api.MessageView.as_view(), name='message'),
    path('api/message_bot/', api.MessageBotView.as_view(), name='message_bot'),
    path('api/message/count/', api.MessageCountView.as_view(), name='message_count'),
    path('api/message_answer/', api.AnswerMessageView.as_view(), name='message_answer'),
    path('api/message_transmission/', api.MessageTransmissionView.as_view(), name='message_transmission'),
    path('api/save_fcm/', api.SaveFCMToken.as_view(), name='save_fcm'),
    path('api/search_user/', api.SearchUserView.as_view(), name='search_user'),
    path('api/current_user/', api.GetCurrentUserView.as_view(), name='current_user'),
    path('api/chat/', api.ChatView.as_view(), name='chat'),
    path('api/group/', api.GroupView.as_view(), name='group'),
    path('api/delete_user_from_group/', api.DeleteUserFromGroup.as_view(), name='delete_user_from_group'),
    path('api/get_chats/', api.GetChatsView.as_view(), name='get_chats'),
    path('api/login/', api.LoginView.as_view(), name='login'),
    path('api/logout/', api.LogoutView.as_view(), name='logout'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    ]
