# Generated by Django 5.1.1 on 2025-05-01 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='Текст')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='Дата')),
                ('in_basket', models.BooleanField(verbose_name='В корзине')),
                ('send_in_basket_id', models.IntegerField(verbose_name="Id сообщения в корзине")),
                ('date_in_basket', models.DateTimeField(verbose_name="Дата отправки в корзину")),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_id_for_message', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_id_for_message', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Spam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='Текст')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='Дата')),
                ('in_basket', models.BooleanField(verbose_name='В корзине')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_id_for_spam', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_id_for_spam', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
