name: Deploy to Yandex Cloud

on:
   push:
      branches:
         - main  # или ваша основная ветка

jobs:
     deploy:
       runs-on: ubuntu-latest

       steps:
       - name: Checkout code
         uses: actions/checkout@v2

       - name: Set up SSH
         uses: webfactory/ssh-agent@v0.5.3
         with:
           ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

       - name: Debug
         run: echo "SSH_PRIVATE_KEY=${{ secrets.SSH_PRIVATE_KEY }}"

       - name: Deploy to server
         run: |
           ssh username@your_server_ip "cd /path/to/your/project && git pull && docker-compose up --build -d"
