name: Deploy Django Project

on:
  push:
    branches:
      - main  # Укажите вашу основную ветку

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t browser .

      - name: Run Docker container
        run: |
          docker run -d --name my_browser -p 80:80 browser

      - name: Wait for the application to start
        run: |
          sleep 10  # Дайте время приложению на запуск

      - name: Get logs
        run: |
          docker logs my_browser

      - name: Stop and remove container
        run: |
          docker stop my_browser 
          docker rm my_browser 
